AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend tienda - Lambdas y API Gateway

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 256
    Timeout: 10
    CodeUri: .
    Environment:
      Variables:
        DB_SECRET_ARN: !Ref DbSecretArn
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
    Policies:
      - Statement:
          - Sid: SecretsManagerAccess
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Ref DbSecretArn

  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Content-Type'"
      AllowMethods: "'GET,POST,OPTIONS'"

Parameters:
  DbSecretArn:
    Type: String
    Description: ARN of Secrets Manager secret with DB credentials
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.health
      Events:
        ApiHealth:
          Type: Api
          Properties:
            Path: /health
            Method: get

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getProducts
      Events:
        ApiGetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.createOrder
      Events:
        ApiCreateOrder:
          Type: Api
          Properties:
            Path: /order
            Method: post

  GetProductsErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Errores en Lambda GetProducts"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetProductsFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - arn:aws:sns:us-east-1:173230496266:prod-tienda-alarms

  CreateOrderErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Errores en Lambda CreateOrder"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: FunctionName
          Value: !Ref CreateOrderFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - arn:aws:sns:us-east-1:173230496266:prod-tienda-alarms
